subscription_id         = "fa0e3cc6-1008-498e-9846-1aa1a116e2f8"
environment_prefix      = "acceptance"
rg_location             = "westeurope"
app_service_plan_name   = "sentia-appserviceplan"
app_service_name        = "sentia-app-service"
cosmosdb_account_name   = "sentia-cosmosdb-account"
mongoDB_name            = "MongoDB"
mongoDB_collection      = "MongoDBCollection"